name: Deploy to GitHub Pages

# Запускаем магию только на пуши в main
on:
  push:
    branches: master
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      # клонируем репозиторий на виртуальную машину
    - uses: actions/checkout@v2
    
      # ставим нужный SDK (можно использовать и более старые)
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'
        include-prerelease: true
        
      # генерируем статические файлы
    - name: Publish .NET Core Project
      run: dotnet publish muazzin_mobile.csproj -c Release --output release --nologo

    - name: Uploading files to gh-pages branch
      uses: muhammadhafiz18/muazzin_mobile-action@4.1.4
      with:
        branch: gh-pages
        folder: release/wwwroot

      # меняем '/' на '/BlazorGitHubPagesDemo/'
    - name: Change base-tag in index.html from / to muazzin_mobile
      run: sed -i 's/<base href="\/" \/>/<base href="\/muazzin_mobile\/" \/>/g' release/wwwroot/index.html

    # отключаем jekyll
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
